### ISSUE TITLE
[FEAT]:Implement Blog Search and Filtering API

### ISSUE THREAD

**Issue by Ibukun-AL** [mufidat3250/Remote_bingo#7]
# Implement Blog Search and Filtering API

## Description

Creating an API that allows visitors to search and filter through blog content on the site without authentication, providing quick access to relevant articles and information.

#### Purpose

To enable users to search and filter blog posts based on various criteria such as author, title, content, tags, and creation date, while implementing robust security measures to protect data and prevent abuse.

#### Requirements

- [ ] Develop a RESTful API endpoint (`GET /api/blogs/search`) to handle requests for searching and filtering blog posts.
- [ ] Implement server-side validation and sanitization of user input to prevent injection attacks and ensure data integrity.
- [ ] Integrate rate limiting to mitigate potential abuse from a single IP address or user.
- [ ] Secure data transmission using HTTPS to protect sensitive information during communication.
- [ ] Implement logging mechanisms to track API requests and responses for auditing and debugging purposes.

#### Expected Outcome

The backend should provide a reliable API endpoint that allows users to search and filter blog content securely and efficiently. It should handle requests based on specified criteria, including content, creation date (`createdDate`), and tags, while adhering to high-security standards.

#### Endpoints

**Fetch Blogs:**

- **Description:** Provides a list of blog posts based on search and filter criteria.
- **Endpoint:** `GET /api/blogs/search`

**Request Parameters:**

- `author`: String (optional) - Author name to filter by.
- `title`: String (optional) - Title or part of a title to filter by.
- `content`: String (optional) - Content or part of the content to filter by.
- `tags`: String (optional) - Tags associated with the blog post to filter by.
- `createdDate`: String (optional) - Date for filtering blog posts created on or after this date (format: YYYY-MM-DD).

**Successful Response:**

```json
[
  {
    "id": "String",
    "title": "String",
    "content": "String",
    "author": "String",
    "createdDate": "String",
    "tags": ["String"]
  }
]
```

### Error Response

```json
{
  "message": "String",
  "error": "String",
  "statusCode": Int
}
```

### Tasks

- [ ] Develop a secure GET endpoint** (`/api/blogs/search`) to fetch blog posts based on search and filter criteria.

- [ ] Ensure server-side validation and sanitization** of user input to prevent security vulnerabilities.

- [ ] Integrate rate limiting middleware** to protect against abuse and maintain API performance.

- [ ] Implement HTTPS protocol** for secure data transmission between client and server.

- [ ] Encrypt sensitive data** such as user information and ensure secure storage in the database.

- [ ] Configure logging** to capture API activities and errors for monitoring and troubleshooting.

### Testing

- Write **comprehensive unit tests** to validate backend logic, including input validation, filtering, and response formatting.
  
- Conduct **integration tests** to verify endpoint functionality and interaction with database queries.
  
- Perform **security testing** to identify and address potential vulnerabilities, ensuring robust data protection measures.
